### ISSUE TITLE
Keypad (Custom) middle-click not work correctly

### ISSUE THREAD

**Issue by jack6th** [Qalculate/qalculate-qt#100]
Qalculate! v4.8.1 on Windows
Reproduce:
In Keypad (Custom) create a button with:
Left-click: Clear expression
Right-click/Long press: Toggle keep above
Middle-click: Clear history
When hover the mouse on the button now the tooltips show all three mouse button clicks are set correctly.
But when I middle-click the button it does not clear history.

**Comment by hanna-kn** [comment]
Fixed.

Right-click action (in this case toggle keep above) were mistakenly used for middle-click (with middle-click action value, which meant that it worked properly if for example middle- and right-click where used for different constants, units, or functions).
