### ISSUE TITLE
Incorrect Labeling of Keyboard Shortcut

### ISSUE THREAD

**Issue by FerretDetective** [Qalculate/qalculate-qt#101]
Right clicking in the expression editing box shows a context menu which mislabels the paste short as "Ctrl+C" instead of the correct "Ctrl+V". The culprit of which I believe to be the following: `pasteAction->setShortcut(QKeySequence::Copy);` on line 1790, in 'src/expressionedit.cpp'.

**Comment by hanna-kn** [comment]
Fixed.
