### ISSUE TITLE
Don't know how to disable overwrite mode

### ISSUE THREAD

**Issue by ludg1e** [Qalculate/qalculate-qt#102]
Hello! I love Qalculate and I always use it for working.

Recently I've noticed that the selection area has overwrite mode enabled, and the insert key doesn't do anything so I can't disable it.
On settings I don't see anything. How can I change it back to typing mode? ([more info](https://www.lenovo.com/my/en/glossary/insert-key/))

OS: Windows 10 22H2
Qalculate: 4.8.1 Qt

![image](https://github.com/Qalculate/qalculate-qt/assets/77110723/075c8cb6-f909-4712-8c07-12e61aa877e6)

Thank you

**Comment by hanna-kn** [comment]
I do not know what could possibly cause this. Overwrite mode is only toggled, in the code, when the Insert key is pressed, and it is not saved on exit.

My only suggestion is that you try to reset all settings by moving or deleting the settings file (c:\Users\<Username>\AppData\Local\Qalculate\qalculate-qt.cfg or qalculate\user\qalculate-qt.cfg depending on if installer was used or not), but I do not expect that it will affect the overwrite mode.

**Comment by ludg1e** [comment]
Somehow now the app is on typing mode, so I guess it's solved.
Closing, thank you!
