### ISSUE TITLE
Saving preferences on exit can fail and then changes are lost

### ISSUE THREAD

**Issue by av-2024** [Qalculate/qalculate-qt#110]
```
OS Name:            Microsoft Windows 10 Pro
OS Version:         10.0.19045 N/A Build 19045
Qt Version:         6.6.0
Qalculate! Version: v4.9.0
```

Just found Qalculate and set it up today. It's pretty awesome (even with this issue, which might be rare). I spent probably 30min getting it set up and tweaking my preferences.

Then I tried to close it. I get an error popup saying it failed to save my preferences and displaying a path to the config file under `C:\Users\myuser\AppData\Local\Qalculate\qalculate-qt.cfg`. There are no permission issues with that path.

I clicked the OK button (the only option).. _and it exited anyway!_ Started it back up and all my preferences are reset.

This is a terrible user experience, especially for using the software for the first time. If I exit and it can't save my preferences for some reason, I should at least get the option to cancel the exit or retry the operation. It shouldn't lose data.

I tried to reproduce the issue with various permutations of changing preferences the same as I did initially, using a workspace, resizing the window, and exiting. Couldn't reproduce it after the first run, even after deleting the local config path.

I hope you will consider adding some robustness to handling the user's data. Also I couldn't find application logs. Is there any logging?

**Comment by hanna-kn** [comment]
I discovered that saving preferences can fail even if there are no issues with the disk or permissions (causing `fopen` to fail) when a workspace (other than the default) is currently open, but the preferences file does not exist (e.g. when the application is first run).

This has now been fixed and I have added a retry option to the error dialog.
