### ISSUE TITLE
Editing units causes all the other names except the first to disappear

### ISSUE THREAD

**Issue by TuulikkiUnelma** [Qalculate/qalculate-qt#111]
Whenever you create a new unit and give it multiple names or abbrevations or such and then save it, the names are kept after pressing "OK". But, if you open the unit afterwards with the "Edit..." button, and then save it, all the names except the first will disappear.

This makes it so that if you want an unit to have more than 1 name (besides the "descriptive name"), you must delete and create it again if you want to change anything about it.

Pictures:

![image](https://github.com/Qalculate/qalculate-qt/assets/88612814/d322d865-41d3-4241-a5be-a078caba525d)
Creating a new unit with 2 names.

![image](https://github.com/Qalculate/qalculate-qt/assets/88612814/3d7af24f-991e-4cf6-8bcc-5a8d4102dc71)
It has both of the names, as it should.

![image](https://github.com/Qalculate/qalculate-qt/assets/88612814/cddeb8f5-468b-45a5-99af-25888bfd3fe5)
The unit is edited.

![image](https://github.com/Qalculate/qalculate-qt/assets/88612814/b1e6d468-0daf-4aff-995a-52d6f86829db)
The additional names are not saved.

**Comment by hanna-kn** [comment]
Fixed (the appropriate behaviour when editing derived unit were mistakenly applied for other types of units instead).
