### ISSUE TITLE
Fahrenheit to Celcius

### ISSUE THREAD

**Issue by peheje** [Qalculate/qalculate-qt#112]
Am I doing something wrong here?

![image](https://github.com/Qalculate/qalculate-qt/assets/7273366/5cd33a7c-d187-4ec4-b18c-bc07ae0488d8)

The UI seems to be correct (despite the many many digits)

![image](https://github.com/Qalculate/qalculate-qt/assets/7273366/5a7ea369-76b8-492f-9c47-f4baf940779e)

v4.9.0 Windows 11

**Comment by hanna-kn** [comment]
Wrong spelling of Cel**s**ius.

**Comment by peheje** [comment]
Omg my bad. Thanks hanna-kn

**Comment by hanna-kn** [comment]
I've now implemented rudimentary detection of potential spelling errors.
```
> -10 Fahrenheit to Celcius

  warning: Did you mean "celsius"?
  −10 fahrenheit ≈ (255.3722222 + 6.817298496i) × (cei μs·C·K·L) / (C·m⁴)
```

**Comment by peheje** [comment]
That's really awesome.
