### ISSUE TITLE
help: where are preferences saved?

### ISSUE THREAD

**Issue by andrearicci** [Qalculate/qalculate-qt#117]
Hi, how can I export all my setup to a new windows machine? (qt)
Thank you

**Comment by andrearicci** [comment]
thnx - I installedit with scoop. I found an "user" folder wich I overwrited with my old copy but no success

**Comment by hanna-kn** [comment]
> thnx - I installedit with scoop. I found an "user" folder wich I overwrited with my old copy but no success

Scoop seems to use the zip files, and replacing the `user` folder (in the `qalculate` directory) should work, unless Qalculate is running while the files are replaced. I recommend that you check the modification time of qalculate-qt.cfg to make sure that you've found the correct folders.

**Comment by andrearicci** [comment]
oh, I understad: scoop uses some hardlink or similar for the user directory so it wasn't copyed on the usb drive…
Thank you
