### ISSUE TITLE
Calculations become slow as the history fills up

### ISSUE THREAD

**Issue by mrxdst** [Qalculate/qalculate-qt#118]
No major issue, just a small inconvenience.

This happens in the qt version but not nearly to the same extend in the gtk version.  
The more calculations you do and with more complicated output, the more sluggish the applications starts to feel.  
When the delay goes above about 0.5-1s it really starts to become noticeable.  
Clearing the history resets the delay.  
This can be reproduced by just typing the expression `rand()` and holding down enter to repeat.

Version 5.0.0 on windows

**Comment by hanna-kn** [comment]
The whole history is reloaded (as an HTML document) each time a new result is added. This has now been improved (only the current result and one previous history item is now updated).
