### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [Qalculate/qalculate-qt#122]
Could you verify the flatpak so people know it's official? Here's a link to the documentation on how to get verified on Flathub https://docs.flathub.org/docs/for-app-authors/verification

**Comment by 0xjmux** [comment]
Would like to echo this: this is what the application looks like in KDE's Discover on Fedora 40. Both the Flathub and "official" fedora release have the same message, each pointing you to the other one. 

![image|400](https://github.com/Qalculate/qalculate-qt/assets/20913473/0f4fd48f-dc0f-4656-bbac-5fff3c15a0df)

**Comment by hanna-kn** [comment]
Done.
