### ISSUE TITLE
Question : Disable Specific SI Unit Prefixes?

### ISSUE THREAD

**Issue by ghrafn** [Qalculate/qalculate-qt#125]
I know this is is probably a strange question, but is there a way to disable certain SI unit prefixes manually? 

Most of the SI unit prefixes are a great help for all the various units.
But personally the “deka (da)” and “hecto (h)” prefixes are just confusing (like converting 10m → 1dam), since they're not commonly used. 
Is there a way to disable these specific prefixes?

Any help would be appreciated! :)

**Comment by hanna-kn** [comment]
They (including centi and deci) are disabled by default for output (Preferences→Units & Currencies→Enable all SI-prefixes). For input, you need to edit prefixes.xml (location depends on operating system and installation method).

**Comment by ghrafn** [comment]
> They (including centi and deci) are disabled by default for automatic use in output (Preferences→Units & Currencies→Enable all SI-prefixes). For input, you need to edit prefixes.xml (location depends on operating system and installation method).

Ah! editing `prefixes.xml` fixed it for me! Thanks! :)

(**for those that are in my shoes** (_I am using Windows 10, and I installed “Qalculate!” using the 64-bit installer_) : I went to `"C:\Program Files\Qalculate\definitions\prefixes.xml"`, 
opened the .xml file using an IDE with administrator privileges, 
and I then commented out the prefixes I didn't want.)
