### ISSUE TITLE
Delay to update to custom font on start on Windows

### ISSUE THREAD

**Issue by anzo42** [Qalculate/qalculate-qt#130]
Hi, I found a small glitch where after setting a `Custom application font` (in my case just a larger version of default Segoe UI) the application doesn't launch with this setting, but after a while it adjusts to the custom setting.
See screen cap below
![FontRHesizeDelay](https://github.com/Qalculate/qalculate-qt/assets/31290050/ba696043-423c-42f4-859e-e93039894f2d)

I checked and all 4.x versions of have this, but up to 4.8 it is barely noticeable. From 4.8 onward it is as in the above gif

Noticed on Windows 10 22H2 x64, Linux's snap version looks ok

UPDATE:
It looks like only the number base view is affected, I enabled the rest of the custom fonts with exaggerated font sizes to easily see the differences, and the rest of GUI looks fine
![FontResizeDelay2](https://github.com/Qalculate/qalculate-qt/assets/31290050/a33e24ca-dfba-418f-9366-ac8d15fca089)

**Comment by hanna-kn** [comment]
Fixed.

**Comment by anzo42** [comment]
That was fast, chapeau bas
![image](https://github.com/Qalculate/qalculate-qt/assets/31290050/c5cb22af-ffdd-4fc6-a5ff-b343f95ea55a)

**Comment by anzo42** [comment]
Just installed 5.2.0, works like a charm. Thanks again.
