### ISSUE TITLE
Incorrect removal of history items

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#132]
1. Right-click in the history area and select `Clear`
2. Type `1`  and press `Enter`
3. Type `2` and press `Enter`
4. Right click on `#2` in the history area and select `Remove`. Instead of removing history item `#2`, Qalculate! duplicates `#1`. An image illustrating the issue:

![incorrect_history_removal](https://github.com/Qalculate/qalculate-qt/assets/24726299/606ce66f-4428-4a81-993b-cc4fae0b27ea)

Additional info: if at step 4 I try to remove item `#1`, Qalculate! duplicates `#2` instead.
 
OS: Windows 10 Home
Qalculate! 5.1.1.

**Comment by hanna-kn** [comment]
Fixed.

This issue occurred when there were exactly one history item left (after clear or remove). The history list was correct after restart.
