### ISSUE TITLE
Incorrect history clearing if there are protected history items

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#133]
This is perhaps related to #132.

1. Right-click in the history area and select `Clear`
2. Type `1` and press `Enter`
3. Type `2` and press `Enter`
4. Right-click on `#2` and select `Protect`
5. Right-click in the history area and select `Clear`. Instead of removing `#1` and leaving `#2`, Qalculate! duplicates `#2`. An image illustrating the issue:

![incorrect_history_clearing](https://github.com/Qalculate/qalculate-qt/assets/24726299/097f8d23-e59d-42ca-a7ca-f31546be8c3e)

OS: Widows 10 Home
Qalculate! 5.1.1.

**Comment by hanna-kn** [comment]
Fixed.

This issue occurred when there were exactly one history item left (after clear or remove). The history list was correct after restart.
