### ISSUE TITLE
Convert toolbar icon doesn't have corresponding text

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#134]
Right-click on the toolbar and select `Text only`. The Convert menu is still displayed as an icon.
An image illustrating the issue:

![toolbar_convert_no_text](https://github.com/Qalculate/qalculate-qt/assets/24726299/29d7581d-d4e6-45ac-a8e6-61482e4c0837)

OS: Windows 10 Home
Qalculate! 5.1.1.

**Comment by hanna-kn** [comment]
Fixed.
