### ISSUE TITLE
Tab completion works incorrectly

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#136]
(This is also true for the GTK version of Qalculate!).

1. Type `ro` and press `Tab`. `ro` gets completed to `roctet`, and that's correct.
2. Press `Tab` again. `roctet` changes to `row()t`, which is incorrect - it should be `row()` instead.

OS: Windows 10 Home
Qalculate! 5.1.1.

**Comment by hanna-kn** [comment]
Fixed (both in qalculate-qt and qalculate-gtk).
