### ISSUE TITLE
A keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#138]
(This is also true for the GTK version).

Type a few numbers and press `Ctrl-)`. Nothing happens, while the combination is bound to `Insert smart parentheses`.

OS: Windows 10 Home
Qalculate! 5.1.1.

**Comment by hanna-kn** [comment]
I'm not able to reproduce this issue. Which keys are pressed for right parenthesis?

**Comment by hanna-kn** [comment]
I'm not able to reproduce this issue? What keyboard layout are you using? Which keys do you press for right parentheses?

**Comment by lkintact** [comment]
I'm using English and Russian layouts. The exact keys I press are `Ctrl`, `Shift` and `0`.

**Comment by lkintact** [comment]
Sorry, there must be something wrong at my side: I just tried binding that combination to a macro in another app and it didn't work.

**Comment by lkintact** [comment]
Turns out the issue was caused by the default Windows 10 combination, `Ctrl-Shift`, for switching keyboard layouts. I switched it to `Не назначено` (`Not Assigned`) and that solved the problem.
Thanks, the issue can be closed, I guess.
