### ISSUE TITLE
Clear History context menu item doesn't do anything

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#139]
1. Type `1` and press `Enter`
2. Right-click in the expression area and select `Clear History`. `Clear History` gets greyed out, but nothing else seems to happen.

OS: Windows 10 Home
Qalculate!: 5.1.1.

**Comment by hanna-kn** [comment]
`Clear History` in the expression context menu empties the expression history accessed using up/down or page up/page down keys. The current contents of the expression field is however not removed from the history.

**Comment by hanna-kn** [comment]
I've now tweaked the behaviour so that the current expression is not temporarily preserved in history when the expression changes, after history clearing.

**Comment by lkintact** [comment]
Got it, thanks for letting know.
