### ISSUE TITLE
Enhancement request: toolbar should be detachable and closable

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#140]
Most of the time I use Qalculate! for very simple math calculations and don't need either toolbar or keypad. Keypad is currently detachable and closable (via `Ctrl-k`), so perhaps should be toolbar.

OS: Windows 10 Home
Qalculate!: 5.1.1.

**Comment by hanna-kn** [comment]
I've now added option to hide toolbar.

I do not think that it would be very useful to be able to detach the toolbar.
