### ISSUE TITLE
Enhancement request: setting the number of expression lines

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#141]
You don't need 3 expression lines for short simple operations (which I personally perform most of the time), so perhaps the number of expression lines should be configurable (which is already the case in the GTK version).
Also, when there's only one expression line, it's easier to see the result as it's displayed closer to the expression area.

Qalculate!: 5.1.1.

**Comment by lkintact** [comment]
Thanks, I knew that, but this is the minimum space the expression area takes on my Windows 10 system, takes about 3 lines:

![expression_area_minimum_space](https://github.com/Qalculate/qalculate-qt/assets/24726299/a91d7c17-b6ad-4ced-98bd-e262f480764f)

**Comment by hanna-kn** [comment]
It seems as if the minimum height of the text edit widget changed in Qt 6. It actually possible to reduce the height to a single row, but it requires a very large font...

This has now been fixed (a custom minimum height equal to one row is set).
