### ISSUE TITLE
Enabling/disabling keypad behavior should probably be changed

### ISSUE THREAD

**Issue by lkintact** [Qalculate/qalculate-qt#142]
1. Suppose we have Qalculate! laid out this way:

![step1](https://github.com/Qalculate/qalculate-qt/assets/24726299/03662900-f377-4ccb-b59e-6bf684868c8f)

2. Press `Ctrl-k` to enable the keypad. The layout changes to this, as expected:

![step2](https://github.com/Qalculate/qalculate-qt/assets/24726299/e6391b7f-3a36-447c-a2cb-7525c9589f5b)

3. Press `Ctrl-k` again to disable the keypad. The layout changes to this:

![step3](https://github.com/Qalculate/qalculate-qt/assets/24726299/e91b37bd-4972-4df5-8c12-7e3d2f9b5236)

Note that now the history area takes more space. Perhaps instead it should be the same size as it was at step 1 - that behavior seems more consistent to me.

Qalculate!: 5.1.1.

**Comment by lkintact** [comment]
FWIW, I observe the same behavior with enabling/disabling the `Number Bases` (`Ctrl-b`) pane.

**Comment by hanna-kn** [comment]
The qalculate-qt interface is not adapted to very small window sizes. I've now added an option to preserve the height of the history area, and a default mode which applies this behaviour when the history area is small. (For a minimized space use, the minimal mode of qalculate-gtk is however superior.)
