### ISSUE TITLE
Version number in qalculate-qt.pro still on 5.1.0

### ISSUE THREAD

**Issue by alyaeanyx** [Qalculate/qalculate-qt#147]
If I'm not mistaken, the version number in qalculate-qt.pro hasn't been incremented in the last release. I believe this leads to the UI showing the wrong version number (screenshot from v5.2.0 tag)

![image](https://github.com/Qalculate/qalculate-qt/assets/74795488/48688de5-9c7c-452c-acf8-0660ae313831)

**Comment by hanna-kn** [comment]
Fixed.
qalculate-qt.pro was not the only place where the version number was not updated. I was really convinced that I had updated the version number in qalculate, but apparently only libqalculate and qalculate-gtk were updated.
