### ISSUE TITLE
Crash after Completion - Wayland

### ISSUE THREAD

**Issue by ariefra** [Qalculate/qalculate-qt#149]
When doing tab completion in qalculate-qt, a crash occur.

**qalculate-qt:** version 5.2.0-1, ~/.config/qalculate-qt deleted (default)

**Host System:** archlinux fully updated as of today
**DE:** plasma-wayland 6.1.2-1
**QT installed:**
qt5-base, qt5-declarative, qt5-feedback, qt5-graphicaleffects, qt5-multimedia, qt5-quickcontrols2, qt5-svg, qt5-translations, qt5-wayland, qt5-x11extras
qt6-5compat, qt6-base, qt6-declarative, qt6-doc, qt6-examples, qt6-imageformats, qt6-multimedia, qt6-multimedia-ffmpeg, qt6-positioning, qt6-sensors, qt6-shadertools, qt6-speech, qt6-svg, qt6-tools, qt6-translations, qt6-virtualkeyboard, qt6-wayland, qt6-webchannel, qt6-webengine, qt6-websockets

**How to replicate:**

Open qalculate-qt from terminal (or anywhere)
type: sin
press tab once
wait till tab completion visible
press tab again to complete (or select with mouse)
qalculate-qt will crash after about 1-2 seconds with Errcode: 255

**Expected behaviour:**
no crash upon completion

**Error message displayed in terminal:**
```
xdg_wm_base#3: error 3: no xdg_popup parent surface has been specified
The Wayland connection experienced a fatal error: Protocol error
```

**Comment by hanna-kn** [comment]
I can confirm the issue on Arch Linux with Qt 6.7.2 on Wayland (both Gnome and Plasma). The crash does however not occur with the qalculate-qt-5.2.0 flatpak package (using Qt 6.6.3).

**Comment by hanna-kn** [comment]
I seem to have fixed issue by setting parent of expression tooltip.
