### ISSUE TITLE
Setting custom fonts causes autocomplete to stop working after restart

### ISSUE THREAD

**Issue by MaCo117** [Qalculate/qalculate-qt#151]
On Windows, settings **Custom expression font** and **Custom application font** causes the autocomplete to stop working after the app is restarted.

Steps to reproduce:
1. Clean install from _qalculate-5.2.0-x64.msi_.
2. Launch **Qalculate! (New)** shortcut.
3. In _Preferences_->_Look & Feel_, check the **Custom expression font** and **Custom application font** checkboxes (no need to actually set a different font).
4. At this point, the autocomplete still works.
5. Restart the app.
6. The autocomplete no longer works.

Qualculate v5.2.0 (Qt) on Windows 10.

**Comment by hanna-kn** [comment]
Fixed.

A possible workaround in v5.2.0 is to create a variable when the application is started (will trigger reloading of the completion list) by appending an appropriate expression to the command (e.g. `qalculate-qt.exe "/store temp"`).
