### ISSUE TITLE
Qt UI: difficulty entering the 'degrees' symbol ° with German keyboard layout on Windows

### ISSUE THREAD

**Issue by Tomalak** [Qalculate/qalculate-qt#158]
**This affects the Qt UI version only.**

**Environment:**

Qalculate 5.2.0 on Windows 10 22H2 (build 19045), system language is "English (United States)" with a "German (IBM)" QWERTZ keyboard layout.

In the German keyboard layout, the degrees symbol is in the top left corner on the combined `^°` key.
![German keyboard layout map](https://github.com/user-attachments/assets/180477bf-5862-4300-94a3-89aa74f10c13)

On this keyboard, the circumflex is a dead key that needs a second key press to actually render the `^`, e.g. pressing <kbd>^°</kbd> and then <kbd>a</kbd> produces `â`.

**Expected behavior:** 

- Pressing <kbd>Shift</kbd>+<kbd>^°</kbd> should give `°` immediately
- Pressing <kbd>^°</kbd> and then <kbd>^°</kbd> again should give `^^`
- Pressing <kbd>^°</kbd> and then <kbd>Space</kbd> should give `^`

**Actual behavior:**

- Pressing <kbd>Shift</kbd>+<kbd>^°</kbd> gives `^` immediately (that's incorrect)
- Pressing <kbd>^°</kbd> and then <kbd>^°</kbd> again gives `^^` (that's correct)
- Pressing <kbd>^°</kbd> and then <kbd>Space</kbd> gives `^` (that's correct)
- Pressing <kbd>^°</kbd> and then<kbd>Shift</kbd>+<kbd>^°</kbd> gives `^°` (that's correct, too, and right now the only way to obtain a `°` symbol in the Qt UI under these circumstances)

**Comment by hanna-kn** [comment]
I have established that this is caused by a workaround which try to achieve the same behaviour as in the Gtk version (where `^` is always input directly, without affecting behaviour with shift, to simplify exponentiation).

I will either fix or remove the attempt (which in other cases does not work at all) to enable direct input of caret using dead circumflex key.

**Comment by hanna-kn** [comment]
Suddenly, after I tried a solution, I'm no longer able to reproduce the issue with the old version (in both Windows 10 and 11, with settings cleared, and after reboot). The behaviour with German keyboard layout in Qt seems somehow random.

**Comment by hanna-kn** [comment]
I've now figured out that the issue was caused by the fact that <kbd>Shift</kbd>+<kbd>^°</kbd> is reported as a non-dead circumflex key press with shift as modifier. The expected behaviour is that a degree key press with shift is reported.

**Comment by Tomalak** [comment]
Awesome, thank you! :)

This seems like a bug in Qt, doesn't it?

**Comment by hanna-kn** [comment]
> This seems like a bug in Qt, doesn't it?

I'm unsure where the cause of the behaviour is. On GNU/Linux the expected degree key is reported for the key press event. The degree key works as expected on both platforms with Swiss keyboard layout. In all cases the input text is correct (`°`) for the event.
