### ISSUE TITLE
Crash when using smart parentheses

### ISSUE THREAD

**Issue by tilse** [Qalculate/qalculate-qt#159]
using smart parentheses after a mathematical operator causes the Interface to become partially unresponsive, requiring a restart.

how to reproduce (this also counts for any other operator):
2+[press smart parentheses]
whereas typing "2+()" does not cause this

expected result:
2+()

platform:
Win10
Qalculate! v5.2.0

**Comment by hanna-kn** [comment]
Fixed.

**Comment by tilse** [comment]
oh nice, so quick! do i have to figure out how to compile this myself or is there a release planned any time soon?

**Comment by hanna-kn** [comment]
A plan to release the next version within 4 weeks.
