### ISSUE TITLE
Percentage Calculation Tool

### ISSUE THREAD

**Issue by devel-2k20** [Qalculate/qalculate-qt#17]
Hello!

Where is in QT gui Percentage Calculation Tool?

![image](https://user-images.githubusercontent.com/92508368/137268128-cd88095a-1c23-4a2e-87d7-ebd03aa07747.png)

**Comment by devel-2k20** [comment]
I would be very much appreciated if you could.
Useful tool for me.

**Comment by hanna-kn** [comment]
Done.
