### ISSUE TITLE
Feature request? Formating in input filed/Expression entry.

### ISSUE THREAD

**Issue by SmallKittyPaws** [Qalculate/qalculate-qt#170]
I can't seem to find a calculator on linux that is formating input numbers similar to how windows does it. I work with big numbers and it's hard to keep track of proper amount of "zeros" you input without help of some sort of separation.

I wanted to try Qalculate instead of standard KDE calcuator in search of this functionality but but think it's not there.

Setting "Display expression status Delay" to zero kind of does what I want. But it stop showing on focus loss and won't pop up until you type something. Making it not very useful in my use case. Wondering if there is a way to just format numbers/data itself on the fly?

**Comment by hanna-kn** [comment]
I've now added an experimental option to group digits in input.

> Setting "Display expression status Delay" to zero kind of does what I want. But it stop showing on focus loss and won't pop up until you type something. Making it not very useful in my use case.

Since version 5.2, the expression status is by default shown in the result list (instead of in a tooltip).

> I work with big numbers and it's hard to keep track of proper amount of "zeros" you input without help of some sort of separation.

Arguably it should be more efficient to use scientific e-notation instead of lots of zeros (e.g. 5e9 instead of 5 000 000 000).

**Comment by SmallKittyPaws** [comment]
> Since version 5.2, the expression status is by default shown in the result list (instead of in a tooltip).

Ah, OpenSUSE repo is stuck at version 5.1. And that's what caused all the problems and confusion. 

Downloaded version 5.3 from Flatpak and now it has all the features I need! Sorry for the mess. I should have checked that first. Still learning the Linux way of doing things, lol
