### ISSUE TITLE
gnuplot not opening but a window flashes

### ISSUE THREAD

**Issue by RandalR** [Qalculate/qalculate-qt#171]
I am trying to get Qalculate to plot. When I click "Add" in the Plot dialog window, another window quickly opens then closes - I've not been able to find out what the window is, or what Qualculate is attempting to open. (is it cmd.exe, or gnuplot.exe or something else?)

I have gnuplot (Version 6.0 patchlevel 1) installed and in the search path. For some reason there is a gnuplot.exe (Version 5.4 patchlevel 3) in the C:\Program Files\Qalculate\ directory that was installed with Qalculate?

Either one will open when called directly, but I don't know what command Qalculate is attempting to execute when I press "Add" in the Plot window. I've tried putting a "pause mouse close" command in the C:\Program Files\gnuplot\share\gnuplotrc file in the hope that it will pause gnuplot when called by Qalculate, but it doesn't seem to be read. The gnuplotrc file is read when I open gnuplot.exe on its own.

I've got this to work in the past, just not on this system and maybe not this version. I'm on Windows 11. I thought for sure that installing gnuplot would fix this, but it behaves as if it wasn't installed.

A bit later, after a bit of investigation with Sysinternal's Process Monitor, I think that qalculate is calling:

`C:\Windows\system32\cmd.exe /c gnuplot - 2>nul  `

the `cmd.exe` is the Windows Command Processor Shell, the `/c` option tells it to run the following program in a new shell then close the shell when the process completes.

of course, `gnuplot` refers to the gnuplot program

the `-` tells gnuplot to accept input from stdin rather than a file

and the `2>nul `means to redirect any errors to the null device where it is discarded.

I wish it would pause before closing whatever it is opening. I also wish that the redirect wasn't there so I could see what - if any - error is occurring.

**Comment by hanna-kn** [comment]
gnuplot.exe is included with Qalculate to avoid the necessity for the user to download and install an additional application to enable plotting. The gnuplot command is called using `_popen` using with without any specified path.

If I think I've found the likely cause for the issue. If the `GNUTERM` environment variable (specified during Gnuplot installation, but by default left unmodified) is set with a value other than "windows" (e.g. "qt" or "wxt"), the Gnuplot binary included with Qalculate won't work (only the "windows" terminal is included).

The solution is to either remove c:\Program Files\Qalculate\gnuplot.exe or unset (remove) the `GNUTERM` environment variable.

**Comment by RandalR** [comment]
Thank you so much for getting back to me so quickly.
I looked, and unfortunately I have the environment variable `GNUTERM=windows` already set.   

I've tried to remove the gnuplot.exe in the qalculate directory, but when I do, the next time I launch the program from the Start Menu, it begins a remove./repair process as if the binary is damaged (I've cancelled out of that quickly so I am not sure what it would do if left to complete).   

If I create a 0 byte file and replace the gnuplot.exe file  (copy con gnuplot.exe then ^Z)  in the qalculate directory, it opens normally and still behaves the same way (window flashing open then close)

**Comment by RandalR** [comment]
I meant to ask, could it be the gnuplot version is 6.0 rather than an earlier one?  I seem to remember seeing a link to gnuplot-5.2.8 somewhere (maybe in the docs?) I will have to try to find that again if you like.

**Comment by RandalR** [comment]
There is not a `c:\users\[USERNAME]\AppData\Roaming\gnuplot.ini` file.

I created an empty one there with that name,  but it had no effect.

**Comment by hanna-kn** [comment]
Another possible workaround might be to replace `C:\Program Files\Qalculate\gnuplot.exe` with `C:\Program Files\gnuplot\gnuplot.exe`.

Are you using the latest version of Qalculate? What is the function you are trying to plot? Have you changed any settings?

**Comment by RandalR** [comment]
I am using version 5.3.0

I did try replacing `C:\Program Files\Qalculate\gnuplot.exe` with the `C:\Program Files\gnuplot\bin\gnuplot.exe` executable to no effect.  Same behavior as before.  
 
I have not made any settings changes in Qalculate or gnuplot other than adding the aforementioned gnuplotrc file in an attempt to diagnose the problem.    
  
I am not familiar with '_popen' - I'm not a developer - I was wondering what options it calls cmd.exe with (other than `/C` that I think I observed), and was wondering if it was possible to replace that switch with `/K` instead so that I could observe what is happening and what error is being generated.

**Comment by RandalR** [comment]
I've solved this issue.

In the registry key `[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor]`, I had added a String Value called ` AutoRun ` which contained a couple of commands I wished to execute each time a Command Prompt window was opened. (see [this entry](https://ss64.com/nt/syntax-autoexec.html) on SS64.com for a quick explanation)
  
Evidently, this was causing the shell called by Qalculate (`C:\Windows\system32\cmd.exe /c gnuplot - 2>nul`  - see above) to either crash, or the command executed by `AutoRun` was returning data that Qalculate was not expecting.

To avoid this sort of problem in the future, Qalculate could call `cmd.exe` with an additional parameter, ` /D ` which will "Disable execution of AutoRun commands from registry".

The steps I followed to resolve this problem were:

1. I uninstalled `gnuplot` and `Qalculate` and deleted all associated files and directories.
2. I then re-installed just `Qalculate`.
3. The problem persisted, so I then removed the `AutoRun` value from the Registry.
4. I reran Qalculate which was then able to plot successfully via the locally-installed copy of `gnuplot.exe`

I apologize if this issue had caused anyone attempting to replicate it to pull their hair out in frustration.  I made this change around the time that I upgraded Qalculate and it did not occur to me that the two things were related.  
  
Thank you for the help!   I adore Qalculate - it is an awesome tool to have handy - and was sad when part of its functionality was not working.

**Comment by hanna-kn** [comment]
> To avoid this sort of problem in the future, Qalculate could call cmd.exe with an additional parameter, /D which will "Disable execution of AutoRun commands from registry".

As I mentioned before Qalculate does not call cmd.exe directly. gnuplot is run using `_popen` which is part of the standard C library on Windows (see https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen).

**Comment by RandalR** [comment]
ok I see.  I didn't know if `_popen` took any arguments (like /C or /K or /D)
