### ISSUE TITLE
Floor function Good!  Ceiling function missing?

### ISSUE THREAD

**Issue by Articus285** [Qalculate/qalculate-qt#172]
Disclaimer: I am relatively new to Qalculate! and still discovering its great features.

Mathematical Floor function is present and workable.

Its kindred function: the Ceiling function seems to be missing.

My attempts to find it did receive suggestions within Qalculate! but nothing pointed me into anything like ceiling( ) function call.

**Comment by hanna-kn** [comment]
Try `ceil`.
