### ISSUE TITLE
Snap package for Qt version

### ISSUE THREAD

**Issue by elcste** [Qalculate/qalculate-qt#31]
I'd love a Snap package of the new Qt version! Happy to help test it if you are interested/able.

(The existing snap of the GTK version has been excellent :1st_place_medal:)

**Comment by hanna-kn** [comment]
Done (https://snapcraft.io/qalculate-qt).

**Comment by elcste** [comment]
Seems to work well. It is not picking up my default font (on GNOME), but I can change the application font in preferences so not a big deal.
