### ISSUE TITLE
New interface - RPN mode - minus operator with keyboard

### ISSUE THREAD

**Issue by fkinnar** [Qalculate/qalculate-qt#32]
It seems impossible to calculate a difference with the keyboard with the new interface (on Windows).

+, / and * work correctly, so do the old interface. 

![Qalculate](https://user-images.githubusercontent.com/45601515/147919928-6fa1149c-e975-4f7c-ac4f-73140616747e.png)

**Comment by hanna-kn** [comment]
Fixed.
