### ISSUE TITLE
Output result with the operators without decimal convertion.

### ISSUE THREAD

**Issue by hellishvictor** [Qalculate/qalculate-qt#33]
Hi
What is the parameter for show the output result and the operators always in hex (without decimal convertion)? I'd found out how to output the result in hex, but the operators are converted to decimal.
Example, with this:
`qalc -b hex 0x517120 + 0x3984A >file.txt`
I get this on "file.txt":
`5337376 + 235594 = 0x55096A`
when I want this:
`0x517120 + 0x3984A = 0x55096A`
Cheers.

**Comment by hanna-kn** [comment]
`qalc -b "hex hex"`
