### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by funnym0nk3y** [Qalculate/qalculate-qt#34]
A really nice addition would be a sort of autocompletion with brackets, so that when pressing enter the top suggestion gets inserted with brackets. Like for example: Typing `sqr` and the pressing enter `sqrt()` gets inserted with the cursor between the brackets. When pressing tab the cursor moves to a defined end position. A lot like it works in vscode.

**Comment by hanna-kn** [comment]
Completed functions are always inserted with brackets.
Tab activates the top suggestion. Enter is not appropriate for this, since it would conflict with its use for expression calculation (regardless of completion status). 
Use end or right arrow key to move beyond the function.

**Comment by funnym0nk3y** [comment]
Ahh, okay, did not know that. Thanks! Muscle memory expected enter, but tab is fine too.
