### ISSUE TITLE
typed text not shown in history (and not saved)

### ISSUE THREAD

**Issue by ngrcld** [Qalculate/qalculate-qt#36]
In qalculate-gtk, the typed text is shown in history, and saved in qalculate-gtk.cfg as "history_expression".
In qalculate-qt, the typed text is NOT shown in history, and NOT saved in qalculate-qt.cfg. Only parsed text is shown and saved.

I'd like an option to show and save typed text (like in qalculate-gtk), not only parsed text.

**Comment by hanna-kn** [comment]
Done (option to show type text instead of or in addition to parsed expression has been added).

Note that the typed text is saved in the history of the expression entry ("expression_history=" in qalculate-qt.cfg).

**Comment by ngrcld** [comment]
thanks!
