### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by vayulove** [Qalculate/qalculate-qt#39]
When I git clone then
```
$ git describe --tags
v4.1.0-3-gba32c38
```
My compiled program's "About Qalculate!" shows V4.0.0 and "Check for Updates" tells me a new version is available.

Do I have 4.1.0 or 4.0.0?

**Comment by hanna-kn** [comment]
When the version number has been updated, in the qalculate-qt.pro file, you need recompile the source (run `make clean` before `make`).

**Comment by vayulove** [comment]
Thanks, it's working great now!  FYI, I love this program!! It's amazing.
