### ISSUE TITLE
Name field in function argument dialog does not work

### ISSUE THREAD

**Issue by char101** [Qalculate/qalculate-qt#44]
Hi,

When adding or editing function argument, the name field does not work.

![2022-06-03 23_35_03-Functions - Qalculate!](https://user-images.githubusercontent.com/71255/171907930-57249387-85c4-4410-a5af-a8265a22d4ec.png)

**Comment by hanna-kn** [comment]
Fixed (probably).

According to my tests it seemed more or less random if the name field worked or not. Double clicking and editing the name column in the argument list did however work as expected.

**Comment by char101** [comment]
I think it because [`item->setData`](https://github.com/Qalculate/qalculate-qt/blob/main/src/functioneditdialog.cpp#L1095) triggers [`FunctionEditDialog::argumentChanged`](https://github.com/Qalculate/qalculate-qt/blob/main/src/functioneditdialog.cpp#L1072) which sets the `arg` name to `item->text()` while `item->text()` is still blank.

So maybe call `item->setText` before `item->setData`?

**Comment by hanna-kn** [comment]
> I think it because [`item->setData`](https://github.com/Qalculate/qalculate-qt/blob/main/src/functioneditdialog.cpp#L1095) triggers [`FunctionEditDialog::argumentChanged`](https://github.com/Qalculate/qalculate-qt/blob/main/src/functioneditdialog.cpp#L1072) which sets the `arg` name to `item->text()` while `item->text()` is still blank.

That was indeed the case.

> So maybe call [`item->setText`](https://github.com/Qalculate/qalculate-qt/blob/main/src/functioneditdialog.cpp#L1096) before `item->setData`?

I chose to use `argumentsModel->blockSignals()` instead (see https://github.com/Qalculate/qalculate-qt/commit/c34eb1d801b5b5b8f96bfcbe8eb347b3e51d3821), but calling `setText` first would also work.
