### ISSUE TITLE
Qalculate (new) gives wrong answers....

### ISSUE THREAD

**Issue by EitanGITHUB** [Qalculate/qalculate-qt#49]
I tried calculating something in qalculate(new) (i will attach some pictures) and for some reason it just freaks out and gives me the wrong answer...
![image](https://user-images.githubusercontent.com/58627502/179920404-1c86537d-24a6-4b1e-96eb-15b307b82f5a.png)
as you can see, im adding 66 to the answer and it gives me a wrong answer, if i only add 6 it works fine, but larger than that its just wrong.
![image](https://user-images.githubusercontent.com/58627502/179921390-86006d7d-ee97-4240-94e5-9b4c67c2b2fa.png)
another picture for reference
![image](https://user-images.githubusercontent.com/58627502/179921473-7dab22e8-f058-4de9-91bb-61046d8b7a2e.png)
another one...
i think this is enough to see there is something wrong XD

**Comment by hanna-kn** [comment]
Input is decimals, output is octal.
52<sub>8</sub> + 10<sub>10</sub> = 42<sub>10</sub> + 10<sub>10</sub> = 52<sub>10</sub> = 64<sub>8</sub>

**Comment by EitanGITHUB** [comment]
Lmao thanks XDD
