### ISSUE TITLE
Unexpected Behavior with Bijective Function

### ISSUE THREAD

**Issue by WeirdOddWodd** [Qalculate/qalculate-qt#50]
Hanna,
I observed an odd behavior with the bijective function. I tried something different from the standard string conversion. I tested some mathematical expressions within the function. The first returned expected output. 2 more tests, however, returned different results than expected. The input bijective("D + A + I + S + Y") returns 58, which is expected (4 + 1 + 9 + 19 + 25 = 58). However, bijective("P + E + A + C + H") returned 158 (16 + 5 + 1 + 3 + 8 = 33). I think that I “figured out” why it returned the incorrect value. Upon pressing the enter key on my keyboard for bijective("P + E + A + C + H"), Qalculate returned the following message: - Misplaced operator(s) "+" ignored. This seems to suggest that the problem is not that “the math was done ‘wrong.’” Rather, at least 1 of the addition operators was ignored, causing the expression to become, for example, bijective("PE + A + C + H) rather than bijective("P + E + A + C + H"). I certainly won’t “complain” about Qalculate!’s “partiality” to Daisy (by both returning the expected 58 for that name and returning a bizarre 158 for Peach). 🤣 However, the expression bijective("P + E + A + C + H") not returning the expected result of 33 is a bit odd. (Incidentally, using separate bijective functions for each letter separated by addition operators did return 33, as expected. The other expression that did not return the expected result was bijective("P + R + I + N + C + E + S + S"). That returns 228 (rather than 103). Interestingly, using Rosalina returns 89 (18 + 15 + 19 + 1 + 12 + 9 + 14 + 1 = 89).

**Comment by hanna-kn** [comment]
Fixed in libqalculate (https://github.com/Qalculate/libqalculate/commit/5578129763e903236fd0297424236ceb26b4ac84).

"+" after "E" was wrongly ignored because of scientific e notation handling (which requires number base between 2 and 10).

This bug has been present at least since version 0.9.7 (from 2010). I'm surprised that it had not been noticed before.

**Comment by WeirdOddWodd** [comment]
I suspected that it was probably related to E or I because of their having separate mathematical uses.

**Comment by WeirdOddWodd** [comment]
I missed the second part of your message (the part about the “dormancy” of the bug) when I read it the first time. I would agree that it is odd that the bug would not have been discovered after 12 years. In future releases, it should have gone from a “dormant” status to an “extinct” status, similar to how Death Mountain <https://zelda-archive.fandom.com/wiki/Death_Mountain>  goes from active to extinct after the defeat of Volvagia <https://zelda-archive.fandom.com/wiki/Volvagia>  (applies while Link is an adult only, however). 🤣
