### ISSUE TITLE
[FR] Highlight entry when Protected

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-qt#51]
I have a wish:
If I protect an entry, I wish that it would stand out from the rest of the history.
Maybe highlight with a bold font, different background (all settings optional) ...?!

Right now, there is no way to see a difference in which values are protected and which are not:
![image](https://user-images.githubusercontent.com/10420187/183568033-c9dc0a5e-0a42-40d6-9522-fbdaba4264b1.png)

**Comment by hanna-kn** [comment]
Done. A padlock will now be shown after protected expressions.

**Comment by foreachthing** [comment]
Thanks! I think, I can see it 😉 
![image](https://user-images.githubusercontent.com/10420187/186069569-f789b9d9-e4ca-4593-aca6-c3f1a01a84d9.png)

Joke aside! Thanks for the padlock!
