### ISSUE TITLE
Hidden Errors - disparity with GTK Qaluculate behaviour.

### ISSUE THREAD

**Issue by ben2talk** [Qalculate/qalculate-qt#52]
With GTK version, when entering `2+3+<Enter>` 
We get:
```
2+3+
- Misplaced operator(s) "+"ignored
```
Useful to see the actual entry, and ignore or correct it.

However, with Qt version the mentioned error no longer visible:
```
2 + 3
--
- Misplaced operator(s) "+" ignored
```
IMO The error should be printed with a note to highlight that it is ignored.

**Comment by hanna-kn** [comment]
The difference between the GTK and the Qt version is the default setting for displayed expression in history. I've now changed the behaviour so that the original expression is always displayed if parsing results in errors or warnings.

**Comment by ben2talk** [comment]
Ah, I found it - Settings>Parsing & Calculation> History (set to Entered+Parsed).
Thank you - I like this Qt version.
