### ISSUE TITLE
Select Font Dialog is behind all of Qalc

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-qt#53]
If the Qalculator is in the middle of the screen and I'd like to choose a different font (for results, expression, ...), the "Select Font" dialog hides behind the "Preferences" AND "Qualculate" window.
Fortunately one can close the dialog with [ESC] and move the windows around first, but this is not ideal.

!Q v4.3.0 on Windows 10/11
I belief, earlier versions had the same behavior.

**Comment by hanna-kn** [comment]
Is "Keep above other windows" enabled?

**Comment by foreachthing** [comment]
> Is "Keep above other windows" enabled?

Ah, yes! :sleeping:
But, I guess, the Select Font dialog should be on top of the Preferences window?!

**Comment by hanna-kn** [comment]
> > Is "Keep above other windows" enabled?
> 
> Ah, yes! :sleeping: 
> But, I guess, the Select Font dialog should be on top of the Preferences window?!

Of course. This has now been fixed.
