### ISSUE TITLE
Typing `if([true, false], x, y)` crashes the program

### ISSUE THREAD

**Issue by DreamweaverOI** [Qalculate/qalculate-qt#59]
I read that you can use vectors as the first and second input of the if-function from the [documentation](https://qalculate.github.io/manual/qalculate-definitions-functions.html#qalculate-definitions-functions-1-Logical), but after I tried it the program seems to crash if it's only used for the first argument.

The crash seems to also happen with other values in the vector, like numbers, but not with variables.

**Comment by hanna-kn** [comment]
Fixed in libqalculate.
