### ISSUE TITLE
Neither function, unit nor variable (de-)activation does not update category trees

### ISSUE THREAD

**Issue by idamir** [Qalculate/qalculate-qt#6]
Action:
- deactivate function, unit or variable
Results:
- function, unit or variable disappears
Expect:
- Inactive category appears immediately
- the function, unit or variable is available under Inactive category
- Inactive category appears after application restart

The same with Activate action.

**Comment by hanna-kn** [comment]
Fixed.

Note that if a global object is deactivated and not replaced, it will reappear after restart.
