### ISSUE TITLE
Prevent escape key from closing application

### ISSUE THREAD

**Issue by ioio85** [Qalculate/qalculate-qt#60]
By default the Escape  key close the application (same as Ctrl+Q), which could be a problem for people who are used to press this key or want this key to do something else.

Current keyboard shortcut redefinition menu option does not let you redefine Esc to anything else. When you redefine an action with Esc key, an error is raised: "Reserved key combination"
![image](https://user-images.githubusercontent.com/20505241/197535205-d281e46a-afda-4519-a306-3840da6d56a4.png)

**Comment by hanna-kn** [comment]
The action of the escape depends on the current state of the application. It aborts a calculation in progress, empties the current expression, or closes the application. It is also used as the standard key for closing menus and dialogs. Application exit is not a common action for the escape key, but can be seen as an extension of its use for closing of dialogs, for some calculator usage patterns.

**Comment by ioio85** [comment]
Thanks for your reply. So if I understand well, there is no way to prevent the esc key to prevent closing the app (like for the gtk frontend) because of its complex use in different part of the gui.

That makes sense to me, I just need get rid of my bad habit that I got from Vim of pressing esc all the time :wink:

**Comment by hanna-kn** [comment]
> So if I understand well, there is no way to prevent the esc key to prevent closing the app (like for the gtk frontend) because of its complex use in different part of the gui.

That is not what exactly what I meant. It should be possible to implement the same behaviour as in the GTK frontend. I actually thought escape closed the application also in the GTK UI, but I remembered wrong (it only closes the main window if the system tray icon is active, on Windows), and now I'm not really sure why it does in the Qt UI...

**Comment by hanna-kn** [comment]
You can add a custom action for the esc key to the configuration file (~/.config/qalculate/qalculate-qt.cfg), e.g. `keyboard_shortcut=Escape 83` (opens the "hamburger" menu).
