### ISSUE TITLE
Russian Federation flag is incorrect

### ISSUE THREAD

**Issue by idamir** [Qalculate/qalculate-qt#61]
The RF flag was corrupted in 4f9bdbbeba0c94b7756a6a5e258085bb8304b717

**Comment by hanna-kn** [comment]
I considered in reenabling the Russian flag, but using https://en.wikipedia.org/wiki/White-blue-white_flag. In the end I decided against it. Since it is of little consequence I've now restored the original flag.

**Comment by idamir** [comment]
A-ha-ha! This is the flag of Sosnovo-Ozerskoe rural settlement really.
