### ISSUE TITLE
Option to style most recent result.

### ISSUE THREAD

**Issue by Doggermelon** [Qalculate/qalculate-qt#73]
I would like to be able to style the most recent result. Currently, Qalculate uses the value of "Custom result font" to style the most recent result but increases its size slightly (by 5 from what I can tell). This causes issues with bitmap fonts that are designed for a specific size as the resolution of the glyphs no longer matches up to the resolution of the screen (the font pictured is [Unifont](http://unifoundry.com/unifont/)):
!["= 25" as the most recent result and penultimate result. The most recent is slightly larger, bluring its lines while the penultimate is crisp.](https://user-images.githubusercontent.com/62311030/209422974-7a6f9ac3-7dd2-4c5f-96a1-1620c9e98eb2.png)
Personally, I'd be happy with a toggle to make the most recent result styled the same as the rest of the result history, but adding a separate font preference for it also solves my problem.

**Comment by hanna-kn** [comment]
qalculate-qt uses `font-size: x-large` for the most recent result (if it fits in on one line). It would be very easy to add an option to not do this, but I assume that superscipts and subscripts (using `<sub>` and `<sup>`), and possible italics, also causes issues with bitmap fonts. Relative font size are also used for error messages.

**Comment by Doggermelon** [comment]
I find the subscript and superscript tolerable as those scale better with my specific font and they aren't the "primary" information, and italics I don't mind as I've only run into them when using unknowns where their appearance isn't as critical to comprehension as numbers are. Same with the error messages, I'm fine with having to read slightly off size bitmap text sometimes as a compromise to being allowed to use them. It's just that with the most recent answer, I encounter off size text every time.

If you're concerned about all the little edge cases of bitmap fonts and potential readability issues, you could also add an option to print answers as unformatted ASCII.

**Comment by hanna-kn** [comment]
I've now added an option to format output (using different font sizes, italics, or sub-/superscript).
