### ISSUE TITLE
Add scoop package

### ISSUE THREAD

**Issue by sbstn87** [Qalculate/qalculate-qt#81]
Hi, 

is it possible to add scoop package for the Qt version of Qalculate? When I install it with scoop, I get only the GTK version.

**Comment by hanna-kn** [comment]
I'm not familiar with scoop packages. It appears (when examining the [json file](https://github.com/ScoopInstaller/Extras/blob/master/bucket/qalculate.json)) as if both binaries are installed, but a shortcut is only created for qalculate-gtk.exe. You should be able to run qalculate-qt.exe from the installation directory and create shortcuts manually.

**Comment by sbstn87** [comment]
Thanks for pointing that out. I have opened an issue at the scoop repo.

**Comment by sbstn87** [comment]
The aforementioned issue has been closed, so the problem seems to be solved. Thanks for your input.
