### ISSUE TITLE
Option(s) to disable unit parsing?

### ISSUE THREAD

**Issue by nick-n-dev** [Qalculate/qalculate-qt#87]
Hi!

Is there any options or anything to disable parsing units entirely? it seems to completely mess up algebraic expressions when using certain letters, such as t.
I'm using the Qt GUI interface, if that matters.

As an example, today i pasted in a Polynomial `(−t^3 + 5t^2 − 6t + 8t^2 − 8t)` to check my work, and in the bottom pane it shows:
`(−(tonne³)) + (5 tonne²) − (6 tonnes) + (8 tonne²) − (8 tonnes)`
as what was parsed...and proceeds to give an obviously nonsensical result.

prefixing all the 't's with \ works as a workaround, but thats kind of tedious, and error-prone.

Apologies if this is a silly question, but i can't find anything in the docs, or options.

(Edit: forgot to mention, i tried disabling every option under Preferences -> Units & Currencies, no dice)

**Comment by nick-n-dev** [comment]
Ah, thank you very much for pointing that out @hanna-kn, i never thought to try the cli commands.
Also apologies, i totally did not notice i was in the qalculate-gtk repo when i posted the issue, my bad! :smile:

**Comment by hanna-kn** [comment]
I've now added both options to the preferences dialog.
