### ISSUE TITLE
holocene calendar

### ISSUE THREAD

**Issue by theedge456** [Qalculate/qalculate-qt#90]
Hello,
It's rather a feature request.
It would be cool if it's not too complex.

Fabien

**Comment by hanna-kn** [comment]
Conversion from Gregorian (ISO 8601) to Holocene calendar (and back) is so simple (add 10 000 years, or 1 in front of modern dates) that I doubt that it would really be a useful feature. If I would add it to the calendar conversion dialog, without also adding any other proposed calendar systems with no current practical use, it might seem as if I am a proponent of the Holocene calendar.
