### ISSUE TITLE
qalculate-qt : Esc Key should not quit Application if calculation screen is empty

### ISSUE THREAD

**Issue by ss005** [Qalculate/qalculate-qt#91]
In **qalculate-qt**, pressing the Esc key clears the calculation screen and **also quits the application if there is nothing in the calculation screen**. This is different from classic qalculate, where pressing Esc only clears the screen and does not quit the application. 

I have unintentionally quit the application many times because of this.

**Steps to reproduce:**
- Open Qalculate! (new).
- Focus on calculation area.
- Press Esc key

**Comment by hanna-kn** [comment]
Duplicate of https://github.com/Qalculate/qalculate-qt/issues/60

**Comment by hanna-kn** [comment]
Fixed.
