### ISSUE TITLE
Sometimes Qalculate keeps running after closing it

### ISSUE THREAD

**Issue by medmedin2014** [Qalculate/qalculate-qt#96]
Sometimes, even if I close Qalculate window, I keep seeing qalculate-qt process running in system monitor.

```
Qalculate!: v4.7.0
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.11-3-MANJARO (64-bit)
Graphics Platform: Wayland
```

**Comment by hanna-kn** [comment]
I also recently noticed this (on Arch Linux). For some reason threads were no longer closed automatically. This should be fixed in version 4.8.0.
