### ISSUE TITLE
base 2 vs base 10 mode switch

### ISSUE THREAD

**Issue by john-cash** [Qalculate/qalculate-qt#99]
absolutely wonderful app. :)

switch to programmer mode, go into binary (base 2).
switch back to general mode, you are still in base 2.  enter something fancy like cbrt(27) or even 27 and you get character '2' was ignored... with base 2, and so on.

not sure if bug or feature.

**Comment by hanna-kn** [comment]
Decimal number base will now be restored after closing the programming keypad.
